#define определить define
#define если if
#define иначе else
#define иначе_если else if
#define пока while
#define для for
#define вернуть return
#define целое int
#define дробное float
#define двойное double
#define символ char
#define строка std::string
#define беззнаковое unsigned
#define константа const
#define статический static
#define класс class
#define структура struct
#define общедоступный public
#define закрытый private
#define защищённый protected
#define виртуальный virtual
#define попытаться try
#define поймать catch
#define бросить throw
#define новый new
#define удалить delete
#define размер sizeof
#define главная main
#define пустота void
